"""Export BC or PPO model to a C header file for STM32 inference.

Supports:
- Standard MLP: 8→H1→H2→2 (ReLU activations)
- Residual bottleneck: 8→16→(4D bottleneck)→16→2 (ReLU + LeakyReLU)
"""
import argparse
import numpy as np
import torch


def export_mlp(weights, biases, output_path):
    """Standard 3-layer MLP: ReLU → ReLU → Linear."""
    W0, W1, W2 = weights
    b0, b1, b2 = biases
    IN, H1 = W0.shape[1], W0.shape[0]
    H2, OUT = W1.shape[0], W2.shape[0]

    print(f"Architecture: {IN} → {H1} → {H2} → {OUT}")
    print(f"Total params: {sum(w.size + b.size for w, b in zip(weights, biases))}")

    def arr_c(name, arr):
        flat = arr.flatten()
        return f"static const float {name}[{len(flat)}] = {{{', '.join(f'{v:.8f}f' for v in flat)}}};"

    lines = []
    lines.append("/* Auto-generated by export_to_c.py — do not edit */")
    lines.append("#ifndef BALANCE_NN_H")
    lines.append("#define BALANCE_NN_H")
    lines.append("")
    lines.append(f"#define NN_INPUT_DIM  {IN}")
    lines.append(f"#define NN_HIDDEN1    {H1}")
    lines.append(f"#define NN_HIDDEN2    {H2}")
    lines.append(f"#define NN_OUTPUT_DIM {OUT}")
    lines.append("")
    lines.append(f"// Layer 0: Linear({IN}, {H1})")
    lines.append(arr_c("nn_w0", W0))
    lines.append(arr_c("nn_b0", b0))
    lines.append("")
    lines.append(f"// Layer 1: Linear({H1}, {H2})")
    lines.append(arr_c("nn_w1", W1))
    lines.append(arr_c("nn_b1", b1))
    lines.append("")
    lines.append(f"// Layer 2: Linear({H2}, {OUT})")
    lines.append(arr_c("nn_w2", W2))
    lines.append(arr_c("nn_b2", b2))
    lines.append("")

    lines.append("static inline void nn_predict(const float* input, float* output) {")
    lines.append(f"    float h0[{H1}];")
    lines.append(f"    float h1[{H2}];")
    lines.append("")
    lines.append("    // Hidden layer 0")
    lines.append(f"    for (int i = 0; i < {H1}; ++i) {{")
    lines.append("        float sum = nn_b0[i];")
    lines.append(f"        for (int j = 0; j < {IN}; ++j) sum += nn_w0[i * {IN} + j] * input[j];")
    lines.append("        h0[i] = (sum > 0.0f) ? sum : 0.0f;  // ReLU")
    lines.append("    }")
    lines.append("")
    lines.append("    // Hidden layer 1")
    lines.append(f"    for (int i = 0; i < {H2}; ++i) {{")
    lines.append("        float sum = nn_b1[i];")
    lines.append(f"        for (int j = 0; j < {H1}; ++j) sum += nn_w1[i * {H1} + j] * h0[j];")
    lines.append("        h1[i] = (sum > 0.0f) ? sum : 0.0f;  // ReLU")
    lines.append("    }")
    lines.append("")
    lines.append("    // Output layer (linear)")
    lines.append(f"    for (int i = 0; i < {OUT}; ++i) {{")
    lines.append("        float sum = nn_b2[i];")
    lines.append(f"        for (int j = 0; j < {H2}; ++j) sum += nn_w2[i * {H2} + j] * h1[j];")
    lines.append("        output[i] = sum;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("#endif")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Saved: {output_path}")

    # Verify
    test = np.array([0.1, -0.05, 0.15, -0.10, 0.02, 0.03, -0.01, 0.0], dtype=np.float32)
    h0 = np.maximum(W0 @ test + b0, 0)
    h1 = np.maximum(W1 @ h0 + b1, 0)
    c_out = W2 @ h1 + b2
    print(f"C output: {c_out}")


def export_residual(state_dict, output_path):
    """Residual bottleneck: 8→16 ReLU → 16→4 LeakyReLU → 4→16 LeakyReLU → + → 16→2."""
    # State dict keys from SB3
    W1 = state_dict["policy.features_extractor.encoder_w"]          # 16×8
    W_down = state_dict["policy.features_extractor.down.weight"]    # 4×16
    W_up = state_dict["policy.features_extractor.up.weight"]        # 16×4
    W2 = state_dict["policy.action_net.weight"]                     # 2×16
    b2 = state_dict["policy.action_net.bias"]                       # 2

    IN, H = W1.shape[1], W1.shape[0]
    B = W_down.shape[0]
    OUT = W2.shape[0]
    assert IN == 8 and H == 16 and B == 4 and OUT == 2

    # Detect if bias is effectively zero
    def arr_c(name, arr):
        flat = arr.flatten()
        return f"static const float {name}[{len(flat)}] = {{{', '.join(f'{v:.8f}f' for v in flat)}}};"

    lines = []
    lines.append("/* Auto-generated by export_to_c.py — do not edit */")
    lines.append("// Architecture: 8→16 ReLU → 16→4 LeakyReLU → 4→16 LeakyReLU → +residual → 16→2")
    lines.append("#ifndef BALANCE_NN_H")
    lines.append("#define BALANCE_NN_H")
    lines.append("")
    lines.append(f"#define NN_INPUT_DIM  {IN}")
    lines.append(f"#define NN_HIDDEN     {H}")
    lines.append(f"#define NN_BOTTLENECK {B}")
    lines.append(f"#define NN_OUTPUT_DIM {OUT}")
    lines.append("")
    lines.append(f"// Encoder: Linear({IN}, {H})")
    lines.append(arr_c("nn_w1", W1))
    lines.append("")
    lines.append(f"// Bottleneck down: Linear({H}, {B})")
    lines.append(arr_c("nn_w_down", W_down))
    lines.append("")
    lines.append(f"// Bottleneck up: Linear({B}, {H})")
    lines.append(arr_c("nn_w_up", W_up))
    lines.append("")
    lines.append(f"// Decoder: Linear({H}, {OUT})")
    lines.append(arr_c("nn_w2", W2))
    lines.append(arr_c("nn_b2", b2))
    lines.append("")

    lines.append("static inline void nn_predict(const float* input, float* output) {")
    lines.append(f"    float h1[{H}];")
    lines.append(f"    float z[{B}];")
    lines.append(f"    float h2[{H}];")
    lines.append("")
    lines.append("    // Encoder: 8→16 ReLU")
    lines.append(f"    for (int i = 0; i < {H}; ++i) {{")
    lines.append("        float sum = 0.0f;")
    lines.append(f"        for (int j = 0; j < {IN}; ++j) sum += nn_w1[i * {IN} + j] * input[j];")
    lines.append("        h1[i] = (sum > 0.0f) ? sum : 0.0f;")
    lines.append("    }")
    lines.append("")
    lines.append("    // Bottleneck: 16→4 LeakyReLU(0.01)")
    lines.append(f"    for (int i = 0; i < {B}; ++i) {{")
    lines.append("        float sum = 0.0f;")
    lines.append(f"        for (int j = 0; j < {H}; ++j) sum += nn_w_down[i * {H} + j] * h1[j];")
    lines.append("        z[i] = (sum > 0.0f) ? sum : 0.01f * sum;")
    lines.append("    }")
    lines.append("")
    lines.append("    // Bottleneck: 4→16 LeakyReLU(0.01) + residual")
    lines.append(f"    for (int i = 0; i < {H}; ++i) {{")
    lines.append("        float sum = 0.0f;")
    lines.append(f"        for (int j = 0; j < {B}; ++j) sum += nn_w_up[i * {B} + j] * z[j];")
    lines.append("        h2[i] = (sum > 0.0f) ? sum : 0.01f * sum;")
    lines.append("        h2[i] += h1[i];  // residual")
    lines.append("    }")
    lines.append("")
    lines.append("    // Decoder: 16→2 linear")
    lines.append(f"    for (int i = 0; i < {OUT}; ++i) {{")
    lines.append("        float sum = nn_b2[i];")
    lines.append(f"        for (int j = 0; j < {H}; ++j) sum += nn_w2[i * {H} + j] * h2[j];")
    lines.append("        output[i] = sum;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("#endif")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Saved: {output_path}")

    # Verify numerically
    test = np.array([0.1, -0.05, 0.15, -0.10, 0.02, 0.03, -0.01, 0.0], dtype=np.float32)
    h1 = np.maximum(W1 @ test, 0)
    z = np.where(W_down @ h1 > 0, W_down @ h1, 0.01 * (W_down @ h1))
    h2 = np.where(W_up @ z > 0, W_up @ z, 0.01 * (W_up @ z)) + h1
    c_out = W2 @ h2 + b2
    print(f"C output: {c_out}")


def export(model_path: str, output_path: str = "balance_nn.h"):
    """Auto-detect architecture and export."""
    if model_path.endswith(".pt") or ("ppo" not in model_path and "best_model" not in model_path):
        # BC model: 8→16→2 with optional standardization
        from pretrain_bc import load_bc_full
        bc, x_m, x_s, y_m, y_s = load_bc_full(model_path)
        state = bc.state_dict()
        W0 = state["net.0.weight"].numpy()
        W2 = state["net.2.weight"].numpy()

        # Bake standardization into weights for C export:
        # h = ReLU(W0 @ ((obs - x_m)/x_s)) = ReLU(W0' @ obs + b0')
        #   where W0' = W0 / x_s, b0' = -W0 @ (x_m / x_s)
        # u = W2 @ h * y_s + y_m = (W2 * y_s) @ h + y_m
        x_mean = x_m.numpy().flatten()
        x_std = x_s.numpy().flatten()
        y_mean = y_m.numpy().flatten()
        y_std = y_s.numpy().flatten()

        W0_baked = W0 / x_std.reshape(1, -1)  # 16×8, column-wise division
        b0_baked = -(W0_baked @ x_mean)        # 16
        W2_baked = W2 * y_std.reshape(-1, 1)   # 2×16, row-wise multiply
        b2_baked = y_mean                       # 2

        # Export as standard MLP: W0_baked(8→16), identity(16→16), W2_baked(16→2)
        b1_zeros = np.zeros(16, dtype=np.float32)
        W1_eye = np.eye(16, dtype=np.float32)
        export_mlp([W0_baked, W1_eye, W2_baked],
                   [b0_baked, b1_zeros, b2_baked], output_path)

    elif "ppo" in model_path or "best_model" in model_path:
        from stable_baselines3 import PPO
        model = PPO.load(model_path, device="cpu")
        sd = {k: v.detach().cpu().numpy() for k, v in model.policy.state_dict().items()}

        # Detect architecture: look for encoder_w in any feature extractor
        residual_keys = [k for k in sd if "encoder_w" in k]
        if residual_keys:
            print("Detected: residual bottleneck architecture")
            # Use pi_features_extractor (SB3 creates separate pi/vf when share_features_extractor=False)
            # Map keys to the format export_residual expects
            prefix = "pi_features_extractor." if "pi_features_extractor." in residual_keys[0] else "features_extractor."
            residual_sd = {
                "policy.features_extractor.encoder_w": sd[f"{prefix}encoder_w"],
                "policy.features_extractor.down.weight": sd[f"{prefix}down.weight"],
                "policy.features_extractor.up.weight": sd[f"{prefix}up.weight"],
                "policy.action_net.weight": sd["action_net.weight"],
                "policy.action_net.bias": sd["action_net.bias"],
            }
            export_residual(residual_sd, output_path)
        else:
            # Standard MLP PPO
            print("Detected: standard MLP architecture")
            weights, biases = [], []
            for name in sorted(sd.keys()):
                if "value" in name:
                    continue
            # Extract in standard order
            actor_keys = [k for k in sd if "value" not in k and ("weight" in k or "bias" in k)]
            w_keys = [k for k in actor_keys if "weight" in k]
            b_keys = [k for k in actor_keys if "bias" in k]
            weights = [sd[k] for k in w_keys]
            biases = [sd[k] for k in b_keys]

            if len(weights) != 3:
                raise RuntimeError(f"Expected 3 weight matrices, got {len(weights)}: {w_keys}")
            export_mlp(weights, biases, output_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export model to C header")
    parser.add_argument("-m", "--model", default="models/bc_model.pt",
                        help="Model path")
    parser.add_argument("-o", "--output",
                        default="WHEELTEC_HAL/MiniBalance/Inc/balance_nn.h",
                        help="Output C header filename")
    args = parser.parse_args()
    export(args.model, args.output)
