"""Export BC (or PPO actor) model to a C header file for STM32 inference."""
import argparse
import numpy as np
import torch
from pretrain_bc import BCModel


def export(model_path: str, output_path: str = "balance_nn.h"):
    """Extract weights and generate C header with nn_predict()."""
    if "ppo" in model_path or "best_model" in model_path:
        # PPO model: extract actor only
        from stable_baselines3 import PPO
        model = PPO.load(model_path, device="cpu")
        actor = model.policy
        layers = []
        for name, param in actor.named_parameters():
            if "value" in name:
                continue
            layers.append((name, param.detach().cpu().numpy()))
    else:
        # BC model
        bc = BCModel()
        bc.load_state_dict(torch.load(model_path, map_location="cpu"))
        layers = [(name, param.detach().cpu().numpy()) for name, param in bc.named_parameters()]

    # Reorder to standard format: w0, b0, w1, b1, w2, b2
    weights = []
    biases = []
    # Extract in order: features.0 → layer0, policy_net.0 → layer1, action_net → layer2
    for name, arr in layers:
        if "weight" in name:
            weights.append(arr)
        elif "bias" in name:
            biases.append(arr)

    if len(weights) != 3:
        raise RuntimeError(f"Expected 3 weight matrices, got {len(weights)}. Layers: {[n for n, _ in layers]}")

    H1, H2 = weights[0].shape[0], weights[1].shape[0]
    OUT = weights[2].shape[0]
    IN = weights[0].shape[1]
    if IN != 8:
        print(f"  WARNING: input dim={IN}, expected 8")
    print(f"Architecture: {IN} → {H1} → {H2} → {OUT}")
    print(f"Total params: {sum(w.size + b.size for w, b in zip(weights, biases))}")

    # --- Generate C header ---
    lines = []
    lines.append("/* Auto-generated by export_to_c.py — do not edit */")
    lines.append("#ifndef BALANCE_NN_H")
    lines.append("#define BALANCE_NN_H")
    lines.append("")
    lines.append(f"#define NN_INPUT_DIM  {IN}")
    lines.append(f"#define NN_HIDDEN1    {H1}")
    lines.append(f"#define NN_HIDDEN2    {H2}")
    lines.append(f"#define NN_OUTPUT_DIM {OUT}")
    lines.append("")

    def arr_c(name, arr):
        flat = arr.flatten()
        vals = ", ".join(f"{v:.8f}f" for v in flat)
        return f"static const float {name}[{len(flat)}] = {{{vals}}};"

    lines.append(f"// Layer 0: Linear({IN}, {H1})")
    lines.append(arr_c("nn_w0", weights[0]))
    lines.append(arr_c("nn_b0", biases[0]))
    lines.append("")
    lines.append(f"// Layer 1: Linear({H1}, {H2})")
    lines.append(arr_c("nn_w1", weights[1]))
    lines.append(arr_c("nn_b1", biases[1]))
    lines.append("")
    lines.append(f"// Layer 2: Linear({H2}, {OUT})")
    lines.append(arr_c("nn_w2", weights[2]))
    lines.append(arr_c("nn_b2", biases[2]))
    lines.append("")

    # Forward pass function
    lines.append("static inline void nn_predict(const float* input, float* output) {")
    lines.append(f"    float h0[{H1}];")
    lines.append(f"    float h1[{H2}];")
    lines.append("")
    lines.append("    // Hidden layer 0")
    lines.append(f"    for (int i = 0; i < {H1}; ++i) {{")
    lines.append("        float sum = nn_b0[i];")
    lines.append(f"        for (int j = 0; j < {IN}; ++j) sum += nn_w0[i * {IN} + j] * input[j];")
    lines.append("        h0[i] = (sum > 0.0f) ? sum : 0.0f;  // ReLU")
    lines.append("    }")
    lines.append("")
    lines.append("    // Hidden layer 1")
    lines.append(f"    for (int i = 0; i < {H2}; ++i) {{")
    lines.append("        float sum = nn_b1[i];")
    lines.append(f"        for (int j = 0; j < {H1}; ++j) sum += nn_w1[i * {H1} + j] * h0[j];")
    lines.append("        h1[i] = (sum > 0.0f) ? sum : 0.0f;  // ReLU")
    lines.append("    }")
    lines.append("")
    lines.append("    // Output layer (linear)")
    lines.append(f"    for (int i = 0; i < {OUT}; ++i) {{")
    lines.append("        float sum = nn_b2[i];")
    lines.append(f"        for (int j = 0; j < {H2}; ++j) sum += nn_w2[i * {H2} + j] * h1[j];")
    lines.append("        output[i] = sum;")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("#endif")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Saved: {output_path}")

    # --- Numerical verification ---
    test_input = np.array(
        [0.1, -0.05, 0.15, -0.10, 0.02, 0.03, -0.01, 0.0],
        dtype=np.float32,
    )

    # C forward using extracted weights
    h0 = np.maximum(weights[0] @ test_input + biases[0], 0)
    h1 = np.maximum(weights[1] @ h0 + biases[1], 0)
    c_out = weights[2] @ h1 + biases[2]

    # Compare against Python model if BC
    if not ("ppo" in model_path or "best_model" in model_path):
        bc = BCModel()
        bc.load_state_dict(torch.load(model_path, map_location="cpu"))
        bc.eval()
        with torch.no_grad():
            py_out = bc(torch.from_numpy(test_input.reshape(1, -1))).numpy().flatten()
        print(f"Python: {py_out}")
        print(f"C:      {c_out}")
        print(f"Match:  {np.allclose(py_out, c_out, atol=1e-5)}")
    else:
        print(f"C output: {c_out}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export model to C header")
    parser.add_argument("-m", "--model", default="bc_model.pt",
                        help="Model path (bc_model.pt or best_model_reg/best_model.zip)")
    parser.add_argument("-o", "--output", default="WHEELTEC_HAL/MiniBalance/Inc/balance_nn.h",
                        help="Output C header filename")
    args = parser.parse_args()
    export(args.model, args.output)
